name: http_wrap
description: "A lightweight Dart and Flutter HTTP wrapper with shared configuration, multipart uploads, and unified responses."
version: 1.1.4
homepage: https://github.com/rans-rans/http_wrap
repository: https://github.com/rans-rans/http_wrap

environment:
  sdk: ^3.12.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.innovations.http_wrap
        pluginClass: HttpWrapPlugin
      ios:
        pluginClass: HttpWrapPlugin
